//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18052
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIN.TECHNICAL.SERVICE_PROCESSOR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360000")]
        public int TIMER_INTERVAL {
            get {
                return ((int)(this["TIMER_INTERVAL"]));
            }
            set {
                this["TIMER_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImportExportServiceLogFenealgest")]
        public string EVENT_LOG {
            get {
                return ((string)(this["EVENT_LOG"]));
            }
            set {
                this["EVENT_LOG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WIN.FENGEST_NAZIONALE.IMPORT_EXPORT.dll,WIN.FENGEST_LOCALE.MAIL_IMPORT.dll")]
        public string PROCESSOR_ASSEMBLY {
            get {
                return ((string)(this["PROCESSOR_ASSEMBLY"]));
            }
            set {
                this["PROCESSOR_ASSEMBLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WIN.FENGEST_NAZIONALE.IMPORT_EXPORT.ImportExportService,WIN.FENGEST_LOCALE.MAIL_I" +
            "MPORT.Processor")]
        public string PROCESSOR_CLASS {
            get {
                return ((string)(this["PROCESSOR_CLASS"]));
            }
            set {
                this["PROCESSOR_CLASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FenealgestImportExportDataService")]
        public string EVENT_LOG_SOURCE {
            get {
                return ((string)(this["EVENT_LOG_SOURCE"]));
            }
            set {
                this["EVENT_LOG_SOURCE"] = value;
            }
        }
    }
}
